/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Estudiante;
import backend.Libro;
import backend.Prestamo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ronyrojas
 */
public class DevolucionLibro extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private Bibliotecario bibliotecario;
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Libro> libros;
    private ArrayList<Prestamo> prestamos;

    /**
     * Creates new form DevolucionLibro
     */
    public DevolucionLibro(Biblioteca biblioteca) {
        initComponents();
        this.biblioteca = biblioteca;
        this.bibliotecario = biblioteca.getBibliotecario();
        this.estudiantes = biblioteca.getEstudiantes();
        this.libros = biblioteca.getLibros();
        this.prestamos = biblioteca.getPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblDevolucionLibro = new javax.swing.JLabel();
        lblCarnetEstudiante = new javax.swing.JLabel();
        fieldCarnetEstudiante = new javax.swing.JTextField();
        lblCodigoLibro = new javax.swing.JLabel();
        fieldCodigoLibro = new javax.swing.JTextField();
        btnCalcularTotal = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        fieldFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 0));
        pnlFrame.setLayout(null);

        lblDevolucionLibro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDevolucionLibro.setForeground(new java.awt.Color(0, 0, 0));
        lblDevolucionLibro.setText("Devolucion Libro");
        pnlFrame.add(lblDevolucionLibro);
        lblDevolucionLibro.setBounds(140, 20, 170, 22);

        lblCarnetEstudiante.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnetEstudiante.setText("Carnet Estudiante:");
        pnlFrame.add(lblCarnetEstudiante);
        lblCarnetEstudiante.setBounds(20, 70, 130, 22);

        fieldCarnetEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCarnetEstudiante);
        fieldCarnetEstudiante.setBounds(20, 90, 180, 30);

        lblCodigoLibro.setForeground(new java.awt.Color(0, 0, 255));
        lblCodigoLibro.setText("Codigo de Libro a Devolver:");
        pnlFrame.add(lblCodigoLibro);
        lblCodigoLibro.setBounds(20, 130, 190, 22);

        fieldCodigoLibro.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCodigoLibro);
        fieldCodigoLibro.setBounds(20, 150, 180, 30);

        btnCalcularTotal.setText("Calcular Total a Pagar");
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCalcularTotal);
        btnCalcularTotal.setBounds(210, 280, 190, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCancelar);
        btnCancelar.setBounds(20, 280, 140, 30);

        fieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldFecha);
        fieldFecha.setBounds(20, 210, 180, 30);

        lblFecha.setForeground(new java.awt.Color(0, 0, 255));
        lblFecha.setText("Fecha de Devolucion:");
        pnlFrame.add(lblFecha);
        lblFecha.setBounds(20, 190, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        // TODO add your handling code here:
        String fecha = fieldFecha.getText();
        int carnetEstudiante = 0;
        String codigoLibro = fieldCodigoLibro.getText();

        if (!fieldCarnetEstudiante.getText().isEmpty()) {
            try {
                carnetEstudiante = Integer.parseInt(fieldCarnetEstudiante.getText());
            } catch (NumberFormatException e) {
                String mensaje = "En el campo: Carnet,\nDebe ingresar un valor numerico entero positivo";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (fieldCarnetEstudiante.getText().isEmpty() || fieldCodigoLibro.getText().isEmpty() || fieldFecha.getText().isEmpty()) {
            String mensaje = "Complete los campos vacios";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (bibliotecario.fechaValida(fecha)) {
                if (bibliotecario.devolverLibro(libros, estudiantes, prestamos, carnetEstudiante, codigoLibro, fecha)) {
                    fieldCarnetEstudiante.setText("");
                    fieldCodigoLibro.setText("");
                    fieldFecha.setText("");
                }
                
            } else {
                String mensaje = "Formato de fecha incorrecto (yyyy-mm-dd)";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField fieldCarnetEstudiante;
    private javax.swing.JTextField fieldCodigoLibro;
    private javax.swing.JTextField fieldFecha;
    private javax.swing.JLabel lblCarnetEstudiante;
    private javax.swing.JLabel lblCodigoLibro;
    private javax.swing.JLabel lblDevolucionLibro;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
