/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author ronyrojas
 */
public class DevolucionLibro extends javax.swing.JFrame {

    /**
     * Creates new form DevolucionLibro
     */
    public DevolucionLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblDevolucionLibro = new javax.swing.JLabel();
        lblCarnetEstudiante = new javax.swing.JLabel();
        fieldCarnetEstudiante = new javax.swing.JTextField();
        lblCodigoLibro = new javax.swing.JLabel();
        fieldCodigoLibro = new javax.swing.JTextField();
        btnCalcularTotal = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 0));
        pnlFrame.setLayout(null);

        lblDevolucionLibro.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblDevolucionLibro.setForeground(new java.awt.Color(0, 0, 0));
        lblDevolucionLibro.setText("Devolucion Libro");
        pnlFrame.add(lblDevolucionLibro);
        lblDevolucionLibro.setBounds(140, 20, 170, 22);

        lblCarnetEstudiante.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnetEstudiante.setText("Carnet Estudiante:");
        pnlFrame.add(lblCarnetEstudiante);
        lblCarnetEstudiante.setBounds(20, 70, 130, 18);

        fieldCarnetEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCarnetEstudiante);
        fieldCarnetEstudiante.setBounds(20, 90, 180, 24);

        lblCodigoLibro.setForeground(new java.awt.Color(0, 0, 255));
        lblCodigoLibro.setText("Codigo de Libro a Devolver:");
        pnlFrame.add(lblCodigoLibro);
        lblCodigoLibro.setBounds(20, 130, 190, 18);

        fieldCodigoLibro.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCodigoLibro);
        fieldCodigoLibro.setBounds(20, 150, 180, 24);

        btnCalcularTotal.setText("Calcular Total a Pagar");
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCalcularTotal);
        btnCalcularTotal.setBounds(210, 250, 190, 24);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCancelar);
        btnCancelar.setBounds(20, 250, 140, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField fieldCarnetEstudiante;
    private javax.swing.JTextField fieldCodigoLibro;
    private javax.swing.JLabel lblCarnetEstudiante;
    private javax.swing.JLabel lblCodigoLibro;
    private javax.swing.JLabel lblDevolucionLibro;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
