/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.ErrorLecturaArchivo;
import backend.Estudiante;
import backend.LeerArchivo;
import backend.Libro;
import backend.Prestamo;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author herberthreyes
 */
public class IngresoArchivo extends javax.swing.JFrame {

    private ArrayList<ErrorLecturaArchivo> erroresEntrada = new ArrayList();
    private ArrayList<Libro> libros;
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Prestamo> prestamos;

    /**
     * Creates new form InterfazIngresoArchivo
     */
    public IngresoArchivo(Biblioteca biblioteca) {
        initComponents();
        //this.biblioteca = biblioteca;
        this.libros = biblioteca.getLibros();
        this.estudiantes = biblioteca.getEstudiantes();
        this.prestamos = biblioteca.getPrestamos();
        jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Subir Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Cargando #");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Leer archivo de entrada");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        jButton2.setText("Libros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Estudiantes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Prestamos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(186, 186, 186))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setVisible(true);
        int res = jFileChooser1.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            LeerArchivo lra = new LeerArchivo(jFileChooser1.getSelectedFile(), this,jLabel1, libros, estudiantes, prestamos);
            lra.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresLibro = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 1) {
                erroresLibro.add(erroresEntrada.get(i));
            }
        }
        ErrorLibro el = new ErrorLibro();
        el.listarErroresLibros(erroresLibro);
        el.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresEstudiante = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 2) {
                erroresEstudiante.add(erroresEntrada.get(i));
            }
        }
        ErrorEstudiante ee = new ErrorEstudiante();
        ee.listarErroresEstudiantes(erroresEstudiante);
        ee.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresPrestamo = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 3) {
                erroresPrestamo.add(erroresEntrada.get(i));
            }
        }
        ErrorPrestamo ep = new ErrorPrestamo();
        ep.listarErroresPrestamos(erroresPrestamo);
        ep.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void verErrores(ArrayList<Libro> librosAnalizados, ArrayList<Estudiante> estudiantesAnalizados,
            ArrayList<Prestamo> prestamosAnalizados, ArrayList<ErrorLecturaArchivo> erroresAnalizados) {

        jButton5.setVisible(true);
        erroresEntrada = erroresAnalizados;

        if (!erroresEntrada.isEmpty()) {
            jLabel1.setText("Ver errores en:");
            boolean errorLibro = false;
            boolean errorEstudiante = false;
            boolean errorPrestamo = false;
            for (int i = 0; i < erroresEntrada.size(); i++) {
                if (erroresEntrada.get(i).getTipo() == 1 && !errorLibro) {
                    errorLibro = true;
                    jButton2.setVisible(true);
                } else if (erroresEntrada.get(i).getTipo() == 2 && !errorEstudiante) {
                    errorEstudiante = true;
                    jButton3.setVisible(true);
                } else if (erroresEntrada.get(i).getTipo() == 3 && !errorPrestamo) {
                    errorPrestamo = true;
                    jButton4.setVisible(true);
                }

                if (errorLibro && errorEstudiante && errorPrestamo) {
                    break;
                }
            }
        } else {
            jLabel1.setText("No hay errores en el archivo de entrada");
        }

        System.out.println("INFORMACION ANALIZADA DEL ARCHIVO DE ENTRADA");
        System.out.println("\n----- LIBROS -----");
        System.out.println("Total de libros: " + librosAnalizados.size());
        System.out.println(librosAnalizados);
        System.out.println("\n----- ESTUDIANTES -----");
        System.out.println("Total de estudiantes: " + estudiantesAnalizados.size());
        System.out.println(estudiantesAnalizados);
        System.out.println("\n----- PRESTAMOS -----");
        System.out.println("Total de prestamos: " + prestamosAnalizados.size());
        System.out.println(prestamosAnalizados);
        System.out.println("\n----- ERRORES -----");
        System.out.println(erroresEntrada);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
