/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.ErrorLecturaArchivo;
import backend.Estudiante;
import backend.LeerArchivo;
import backend.Libro;
import backend.Prestamo;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author herberthreyes
 */
public class InterfazIngresoArchivo extends javax.swing.JFrame {

    private ArrayList<ErrorLecturaArchivo> erroresEntrada = new ArrayList();
    private ArrayList<Libro> librosEntrada = new ArrayList();
    private ArrayList<Estudiante> estudiantesEntrada = new ArrayList();
    private ArrayList<Prestamo> prestamosEntrada = new ArrayList();

    /**
     * Creates new form InterfazIngresoArchivo
     */
    public InterfazIngresoArchivo() {
        initComponents();
        //this.setLocationRelativeTo(null);
        jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Subir Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Cargando #");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("BIBLIOTECA - CUNOC");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        jButton2.setText("Libros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Estudiantes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Prestamos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Ir al Menú Principal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setVisible(true);
        int res = jFileChooser1.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            LeerArchivo lra = new LeerArchivo();
            lra.setArchivoEntrada(jFileChooser1.getSelectedFile());
            lra.setIia(this);
            lra.setLblCarga(jLabel1);
            lra.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresLibro = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 1) {
                erroresLibro.add(erroresEntrada.get(i));
            }
        }
        ErrorLibro el = new ErrorLibro();
        el.listarErroresLibros(erroresLibro);
        el.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresEstudiante = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 2) {
                erroresEstudiante.add(erroresEntrada.get(i));
            }
        }
        ErrorEstudiante ee = new ErrorEstudiante();
        ee.listarErroresEstudiantes(erroresEstudiante);
        ee.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<ErrorLecturaArchivo> erroresPrestamo = new ArrayList();
        for (int i = 0; i < erroresEntrada.size(); i++) {
            if (erroresEntrada.get(i).getTipo() == 3) {
                erroresPrestamo.add(erroresEntrada.get(i));
            }
        }
        ErrorPrestamo ep = new ErrorPrestamo();
        ep.listarErroresPrestamos(erroresPrestamo);
        ep.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal ip = new InterfazPrincipal();
        this.dispose();
        ip.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    public void verErrores(ArrayList<Libro> librosAnalizados, ArrayList<Estudiante> estudiantesAnalizados,
            ArrayList<Prestamo> prestamosAnalizados, ArrayList<ErrorLecturaArchivo> erroresAnalizados) {

        jButton5.setVisible(true);
        librosEntrada = librosAnalizados;
        estudiantesEntrada = estudiantesAnalizados;
        prestamosEntrada = prestamosAnalizados;
        erroresEntrada = erroresAnalizados;

        if (!erroresEntrada.isEmpty()) {
            jLabel1.setText("Ver errores en:");
            boolean errorLibro = false;
            boolean errorEstudiante = false;
            boolean errorPrestamo = false;
            for (int i = 0; i < erroresEntrada.size(); i++) {
                if (erroresEntrada.get(i).getTipo() == 1 && !errorLibro) {
                    errorLibro = true;
                    jButton2.setVisible(true);
                } else if (erroresEntrada.get(i).getTipo() == 2 && !errorEstudiante) {
                    errorEstudiante = true;
                    jButton3.setVisible(true);
                } else if (erroresEntrada.get(i).getTipo() == 3 && !errorPrestamo) {
                    errorPrestamo = true;
                    jButton4.setVisible(true);
                }

                if (errorLibro && errorEstudiante && errorPrestamo) {
                    break;
                }
            }
        } else {
            jLabel1.setText("No hay errores en el archivo de entrada");
        }

        System.out.println("\n----- LIBROS -----");
        System.out.println("Total de libros: " + librosEntrada.size());
        System.out.println(librosEntrada);
        System.out.println("\n----- ESTUDIANTES -----");
        System.out.println("Total de estudiantes: " + estudiantesEntrada.size());
        System.out.println(estudiantesEntrada);
        System.out.println("\n----- PRESTAMOS -----");
        System.out.println("Total de prestamos: " + prestamosEntrada.size());
        System.out.println(prestamosEntrada);
        System.out.println("\n----- ERRORES -----");
        System.out.println(erroresEntrada);
    }

    public ArrayList<Libro> getLibrosEntrada() {
        return librosEntrada;
    }

    public void setLibrosEntrada(ArrayList<Libro> librosEntrada) {
        this.librosEntrada = librosEntrada;
    }

    public ArrayList<Estudiante> getEstudiantesEntrada() {
        return estudiantesEntrada;
    }

    public void setEstudiantesEntrada(ArrayList<Estudiante> estudiantesEntrada) {
        this.estudiantesEntrada = estudiantesEntrada;
    }

    public ArrayList<Prestamo> getPrestamosEntrada() {
        return prestamosEntrada;
    }

    public void setPrestamosEntrada(ArrayList<Prestamo> prestamosEntrada) {
        this.prestamosEntrada = prestamosEntrada;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazIngresoArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazIngresoArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazIngresoArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazIngresoArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazIngresoArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
