/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.ControladorArchivoBinario;
import backend.Estudiante;
import backend.Libro;
import backend.Prestamo;
import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author herberthreyes
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    ControladorArchivoBinario cab = new ControladorArchivoBinario();
    File archivoBinario = new File("./biblioteca.bin");
    private ArrayList<Libro> libros;
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Prestamo> prestamos;
    private Biblioteca biblioteca;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        Biblioteca bibliotecaArchivoBinario = cab.leerBibliotecaGuardada(archivoBinario);
        if (bibliotecaArchivoBinario != null) {
            this.biblioteca = bibliotecaArchivoBinario;
            libros = bibliotecaArchivoBinario.getLibros();
            estudiantes = bibliotecaArchivoBinario.getEstudiantes();
            prestamos = bibliotecaArchivoBinario.getPrestamos();
        } else {
            this.biblioteca = new Biblioteca();
            libros = new ArrayList();
            estudiantes = new ArrayList();
            prestamos = new ArrayList();
        }
        this.biblioteca.setLibros(libros);
        this.biblioteca.setEstudiantes(estudiantes);
        this.biblioteca.setPrestamos(prestamos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pnlFrame = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        comboBoxReportes = new javax.swing.JComboBox<>();
        lblReportes = new javax.swing.JLabel();
        btnGuardarInformacion = new javax.swing.JButton();
        lblAlmacenarInfo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        itemRegistrarLibro = new javax.swing.JMenuItem();
        itemRegistrarEstudiante = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        itemPrestarLibro = new javax.swing.JMenuItem();
        itemDevolverLibro = new javax.swing.JMenuItem();
        menuImportarDatos = new javax.swing.JMenu();
        itemLeerArchivo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(101, 150, 164));
        pnlFrame.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("BIBLIOTECA - CUNOC");
        pnlFrame.add(lblTitulo);
        lblTitulo.setBounds(290, 20, 220, 50);

        comboBoxReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Prestamos de libros a entregar hoy", "2. Prestamos de libros con demora", "3. Dinero recaudado en intervalo de tiempo", "4. Todos los prestamos hechos a un estudiante", "5. Libros prestados actualmente a un estudiante", "6. Prestamos hechos a cada carrera en intervalo de tiempo" }));
        comboBoxReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxReportesActionPerformed(evt);
            }
        });
        pnlFrame.add(comboBoxReportes);
        comboBoxReportes.setBounds(230, 100, 320, 40);

        lblReportes.setForeground(new java.awt.Color(0, 0, 0));
        lblReportes.setText("Reportes");
        pnlFrame.add(lblReportes);
        lblReportes.setBounds(360, 80, 90, 22);

        btnGuardarInformacion.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btnGuardarInformacion.setText("Guardar");
        btnGuardarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInformacionActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGuardarInformacion);
        btnGuardarInformacion.setBounds(320, 470, 120, 40);

        lblAlmacenarInfo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblAlmacenarInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblAlmacenarInfo.setText("Almacenar informacion");
        pnlFrame.add(lblAlmacenarInfo);
        lblAlmacenarInfo.setBounds(280, 430, 210, 22);

        menuRegistrar.setText("Registrar");

        itemRegistrarLibro.setText("Libro");
        itemRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarLibroActionPerformed(evt);
            }
        });
        menuRegistrar.add(itemRegistrarLibro);

        itemRegistrarEstudiante.setText("Estudiante");
        itemRegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarEstudianteActionPerformed(evt);
            }
        });
        menuRegistrar.add(itemRegistrarEstudiante);

        menuBar.add(menuRegistrar);

        menuPrestamos.setText("Prestamos");
        menuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestamosActionPerformed(evt);
            }
        });

        itemPrestarLibro.setText("Prestar Libro");
        itemPrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrestarLibroActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemPrestarLibro);

        itemDevolverLibro.setText("Devolver Libro");
        itemDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDevolverLibroActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemDevolverLibro);

        menuBar.add(menuPrestamos);

        menuImportarDatos.setText("Importar Datos");

        itemLeerArchivo.setText("Leer archivo de entrada");
        itemLeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLeerArchivoActionPerformed(evt);
            }
        });
        menuImportarDatos.add(itemLeerArchivo);

        menuBar.add(menuImportarDatos);

        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        menuBar.add(menuAyuda);

        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuBar.add(menuAcercaDe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarLibroActionPerformed
        // TODO add your handling code here:
        RegistroLibro registrarLibro = new RegistroLibro(biblioteca);
        registrarLibro.setVisible(true);
    }//GEN-LAST:event_itemRegistrarLibroActionPerformed

    private void itemRegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarEstudianteActionPerformed
        // TODO add your handling code here:
        RegistroEstudiante registrarEstudiante = new RegistroEstudiante(biblioteca);
        registrarEstudiante.setVisible(true);
    }//GEN-LAST:event_itemRegistrarEstudianteActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void comboBoxReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxReportesActionPerformed
        // TODO add your handling code here:
        int numeroReporte = comboBoxReportes.getSelectedIndex() + 1;

        switch (numeroReporte) {
            case 1:
                Reporte1 reporte1 = new Reporte1(biblioteca);
                reporte1.setVisible(true);
                break;
            case 2:
                Reporte2 reporte2 = new Reporte2(biblioteca);
                reporte2.setVisible(true);
                break;
            case 3:
                Reporte3 reporte3 = new Reporte3(biblioteca);
                reporte3.setVisible(true);
                break;
            case 4:
                Reporte4 reporte4 = new Reporte4(biblioteca);
                reporte4.setVisible(true);
                break;
            case 5:
                Reporte5 reporte5 = new Reporte5(biblioteca);
                reporte5.setVisible(true);
                break;
            case 6:
                Reporte6 reporte6 = new Reporte6(biblioteca);
                reporte6.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_comboBoxReportesActionPerformed


    private void btnGuardarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInformacionActionPerformed
        // TODO add your handling code here:
        cab.guardarBiblioteca(biblioteca, archivoBinario);
        //cab.leerBibliotecaGuardada(archivoBinario);
    }//GEN-LAST:event_btnGuardarInformacionActionPerformed

    private void menuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPrestamosActionPerformed

    private void itemPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrestarLibroActionPerformed
        // TODO add your handling code here:
        PrestamoLibro prestamo = new PrestamoLibro(biblioteca);
        prestamo.setVisible(true);
    }//GEN-LAST:event_itemPrestarLibroActionPerformed

    private void itemDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDevolverLibroActionPerformed
        // TODO add your handling code here:
        DevolucionLibro devolucion = new DevolucionLibro(biblioteca);
        devolucion.setVisible(true);
    }//GEN-LAST:event_itemDevolverLibroActionPerformed

    private void itemLeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLeerArchivoActionPerformed
        // TODO add your handling code here:
        IngresoArchivo ia = new IngresoArchivo(biblioteca);
        ia.setVisible(true);
    }//GEN-LAST:event_itemLeerArchivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarInformacion;
    private javax.swing.JComboBox<String> comboBoxReportes;
    private javax.swing.JMenuItem itemDevolverLibro;
    private javax.swing.JMenuItem itemLeerArchivo;
    private javax.swing.JMenuItem itemPrestarLibro;
    private javax.swing.JMenuItem itemRegistrarEstudiante;
    private javax.swing.JMenuItem itemRegistrarLibro;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblAlmacenarInfo;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuImportarDatos;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
