/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Libro;
import java.util.ArrayList;

/**
 *
 * @author herberthreyes
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private ArrayList<Libro> libros;
    private Bibliotecario bibliotecario;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal(Biblioteca biblioteca) {
        initComponents();
        //this.setLocationRelativeTo(null);

        this.biblioteca = biblioteca;
        libros = biblioteca.getLibros();
        bibliotecario = biblioteca.getBibliotecario();
        
        /*menuBar.setVisible(false);
        lblReportes.setVisible(false);
        lblAlmacenarInfo.setVisible(false);
        comboBoxReportes.setVisible(false);
        btnGuardarLibros.setVisible(false);
        btnGuardarEstudiantes.setVisible(false);
        btnGuardarPrestamos.setVisible(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        pnlFrame = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        comboBoxReportes = new javax.swing.JComboBox<>();
        lblReportes = new javax.swing.JLabel();
        btnGuardarLibros = new javax.swing.JButton();
        btnGuardarEstudiantes = new javax.swing.JButton();
        btnGuardarPrestamos = new javax.swing.JButton();
        lblAlmacenarInfo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        itemRegistrarLibro = new javax.swing.JMenuItem();
        itemRegistrarEstudiante = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        itemPrestarLibro = new javax.swing.JMenuItem();
        itemDevolverLibro = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(101, 150, 164));
        pnlFrame.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("BIBLIOTECA - CUNOC");
        pnlFrame.add(lblTitulo);
        lblTitulo.setBounds(290, 20, 220, 50);

        comboBoxReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prestamos de libros a entregar hoy", "Prestamos de libros con mora", "Dinero recaudado en intervalo de tiempo", "Todos los prestamos hechos a un estudiante", "Prestamos actuales a un estudiante", "Prestamos hechos a cada carrera en intervalo de tiempo" }));
        comboBoxReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxReportesActionPerformed(evt);
            }
        });
        pnlFrame.add(comboBoxReportes);
        comboBoxReportes.setBounds(230, 100, 320, 40);

        lblReportes.setForeground(new java.awt.Color(0, 0, 0));
        lblReportes.setText("Reportes");
        pnlFrame.add(lblReportes);
        lblReportes.setBounds(360, 80, 90, 18);

        btnGuardarLibros.setText("Libros");
        btnGuardarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibrosActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGuardarLibros);
        btnGuardarLibros.setBounds(220, 460, 120, 40);

        btnGuardarEstudiantes.setText("Estudiantes");
        btnGuardarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstudiantesActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGuardarEstudiantes);
        btnGuardarEstudiantes.setBounds(340, 460, 120, 40);

        btnGuardarPrestamos.setText("Prestamos");
        btnGuardarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPrestamosActionPerformed(evt);
            }
        });
        pnlFrame.add(btnGuardarPrestamos);
        btnGuardarPrestamos.setBounds(460, 460, 120, 40);

        lblAlmacenarInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblAlmacenarInfo.setText("Almacenar informacion");
        pnlFrame.add(lblAlmacenarInfo);
        lblAlmacenarInfo.setBounds(330, 430, 150, 18);

        menuRegistrar.setText("Registrar");

        itemRegistrarLibro.setText("Libro");
        itemRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarLibroActionPerformed(evt);
            }
        });
        menuRegistrar.add(itemRegistrarLibro);

        itemRegistrarEstudiante.setText("Estudiante");
        itemRegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarEstudianteActionPerformed(evt);
            }
        });
        menuRegistrar.add(itemRegistrarEstudiante);

        menuBar.add(menuRegistrar);

        menuPrestamos.setText("Prestamos");
        menuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrestamosActionPerformed(evt);
            }
        });

        itemPrestarLibro.setText("Prestar Libro");
        itemPrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrestarLibroActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemPrestarLibro);

        itemDevolverLibro.setText("Devolver Libro");
        itemDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDevolverLibroActionPerformed(evt);
            }
        });
        menuPrestamos.add(itemDevolverLibro);

        menuBar.add(menuPrestamos);

        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        menuBar.add(menuAyuda);

        menuAcercaDe.setText("Acerca de");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuBar.add(menuAcercaDe);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarLibroActionPerformed
        // TODO add your handling code here:
        RegistroLibro registrarLibro = new RegistroLibro(biblioteca);
        registrarLibro.setVisible(true);
    }//GEN-LAST:event_itemRegistrarLibroActionPerformed

    private void itemRegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarEstudianteActionPerformed
        // TODO add your handling code here:
        RegistroEstudiante registrarEstudiante = new RegistroEstudiante(biblioteca);
        registrarEstudiante.setVisible(true);
    }//GEN-LAST:event_itemRegistrarEstudianteActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void comboBoxReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxReportesActionPerformed


    private void btnGuardarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibrosActionPerformed
        // TODO add your handling code here:
        System.out.println(libros.toString());
    }//GEN-LAST:event_btnGuardarLibrosActionPerformed

    private void btnGuardarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarEstudiantesActionPerformed

    private void btnGuardarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPrestamosActionPerformed

    private void menuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPrestamosActionPerformed

    private void itemPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrestarLibroActionPerformed
        // TODO add your handling code here:
        PrestamoLibro prestamo = new PrestamoLibro(biblioteca);
        prestamo.setVisible(true);
    }//GEN-LAST:event_itemPrestarLibroActionPerformed

    private void itemDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDevolverLibroActionPerformed
        // TODO add your handling code here:
        DevolucionLibro devolucion = new DevolucionLibro();
        devolucion.setVisible(true);
    }//GEN-LAST:event_itemDevolverLibroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEstudiantes;
    private javax.swing.JButton btnGuardarLibros;
    private javax.swing.JButton btnGuardarPrestamos;
    private javax.swing.JComboBox<String> comboBoxReportes;
    private javax.swing.JMenuItem itemDevolverLibro;
    private javax.swing.JMenuItem itemPrestarLibro;
    private javax.swing.JMenuItem itemRegistrarEstudiante;
    private javax.swing.JMenuItem itemRegistrarLibro;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblAlmacenarInfo;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
