/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Estudiante;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronyrojas
 */
public class ListadoEstudiantes extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private ArrayList<Estudiante> estudiantes;
    private Bibliotecario bibliotecario;

    /**
     * Creates new form ListadoEstudiantes
     */
    public ListadoEstudiantes(Biblioteca biblioteca) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.biblioteca = biblioteca;
        this.bibliotecario = biblioteca.getBibliotecario();
        this.estudiantes = biblioteca.getEstudiantes();

        DefaultTableModel modeloTabla = (DefaultTableModel) tblListado.getModel();
        bibliotecario.ordenarEstudiantes(estudiantes);
        for (Estudiante estudiante : estudiantes) {
            modeloTabla.addRow(new Object[]{
                estudiante.getCarnet(),
                estudiante.getNombre(),
                estudiante.getCodigoCarrera(),
                estudiante.getFechaNacimiento()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblListadoEstudiantes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        lblFiltrar = new javax.swing.JLabel();
        comboBoxFiltros = new javax.swing.JComboBox<>();
        lblBusqueda = new javax.swing.JLabel();
        fieldBusqueda = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiarFiltro = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 153));
        pnlFrame.setLayout(null);

        lblListadoEstudiantes.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblListadoEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        lblListadoEstudiantes.setText("Listado De Estudiantes Existentes:");
        pnlFrame.add(lblListadoEstudiantes);
        lblListadoEstudiantes.setBounds(350, 20, 330, 22);

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Codigo Carrera", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListado);

        pnlFrame.add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 940, 402);

        lblFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltrar.setText("Filtrar por:");
        pnlFrame.add(lblFiltrar);
        lblFiltrar.setBounds(30, 500, 70, 20);

        comboBoxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet", "Nombre", "Codigo de Carrera" }));
        pnlFrame.add(comboBoxFiltros);
        comboBoxFiltros.setBounds(140, 500, 130, 24);

        lblBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lblBusqueda.setText("Item a buscar:");
        pnlFrame.add(lblBusqueda);
        lblBusqueda.setBounds(30, 550, 100, 18);
        pnlFrame.add(fieldBusqueda);
        fieldBusqueda.setBounds(140, 550, 130, 24);

        btnFiltrar.setText("Aplicar Filtro");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnFiltrar);
        btnFiltrar.setBounds(140, 600, 130, 24);

        btnLimpiarFiltro.setText("Limpiar Filtro");
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltroActionPerformed(evt);
            }
        });
        pnlFrame.add(btnLimpiarFiltro);
        btnLimpiarFiltro.setBounds(310, 600, 130, 24);

        btnCerrar.setText("Cerrar Listado");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCerrar);
        btnCerrar.setBounds(830, 590, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltroActionPerformed
        // TODO add your handling code here:
        fieldBusqueda.setText("");
    }//GEN-LAST:event_btnLimpiarFiltroActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiarFiltro;
    private javax.swing.JComboBox<String> comboBoxFiltros;
    private javax.swing.JTextField fieldBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblListadoEstudiantes;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
