/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Filtro;
import backend.Libro;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronyrojas
 */
public class ListadoLibros extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private ArrayList<Libro> libros;
    private Bibliotecario bibliotecario = new Bibliotecario();
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form ListadoLibros
     */
    public ListadoLibros(Biblioteca biblioteca) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.biblioteca = biblioteca;
        this.libros = biblioteca.getLibros();
        
        modeloTabla = (DefaultTableModel) tblListado.getModel();        
        bibliotecario.ordenarLibros(libros);        
        for (Libro libro : libros) {
            modeloTabla.addRow(new Object[] {
            libro.getCodigo(),
            libro.getAutor(),
            libro.getTitulo(),
            libro.getCantidad(),
            libro.getFechaPublicacion(),
            libro.getEditorial()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        lblListadoLibros = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        fieldCodigo = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        fieldAutor = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        fieldTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 153));
        pnlFrame.setLayout(null);

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Autor", "Titulo", "Copias", "Fecha Publicacion", "Editorial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListado);

        pnlFrame.add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 930, 402);

        lblListadoLibros.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblListadoLibros.setForeground(new java.awt.Color(0, 0, 0));
        lblListadoLibros.setText("Listado De Libros Existentes");
        pnlFrame.add(lblListadoLibros);
        lblListadoLibros.setBounds(360, 20, 270, 22);

        lblFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltrar.setText("Filtrar por:");
        pnlFrame.add(lblFiltrar);
        lblFiltrar.setBounds(40, 520, 90, 20);

        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código:");
        pnlFrame.add(lblCodigo);
        lblCodigo.setBounds(40, 570, 70, 30);

        btnCerrar.setText("Cerrar Listado");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCerrar);
        btnCerrar.setBounds(790, 590, 160, 40);

        fieldCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCodigoKeyReleased(evt);
            }
        });
        pnlFrame.add(fieldCodigo);
        fieldCodigo.setBounds(130, 570, 130, 30);

        lblAutor.setForeground(new java.awt.Color(0, 0, 0));
        lblAutor.setText("Autor:");
        pnlFrame.add(lblAutor);
        lblAutor.setBounds(290, 570, 47, 30);

        fieldAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldAutorKeyReleased(evt);
            }
        });
        pnlFrame.add(fieldAutor);
        fieldAutor.setBounds(350, 570, 140, 30);

        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Título:");
        pnlFrame.add(lblTitulo);
        lblTitulo.setBounds(530, 570, 58, 30);

        fieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldTituloKeyReleased(evt);
            }
        });
        pnlFrame.add(fieldTitulo);
        fieldTitulo.setBounds(600, 570, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void fieldCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCodigoKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_fieldCodigoKeyReleased

    private void fieldAutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldAutorKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_fieldAutorKeyReleased

    private void fieldTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTituloKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_fieldTituloKeyReleased

    private void filtrar(){
        Filtro filtro = new Filtro();
        filtro.filtroLibros(tblListado.getRowCount(), fieldCodigo.getText(), fieldAutor.getText(), fieldTitulo.getText(), modeloTabla, libros);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JTextField fieldAutor;
    private javax.swing.JTextField fieldCodigo;
    private javax.swing.JTextField fieldTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblListadoLibros;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
