/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Libro;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronyrojas
 */
public class ListadoLibros extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private ArrayList<Libro> libros;
    private Bibliotecario bibliotecario;

    /**
     * Creates new form ListadoLibros
     */
    public ListadoLibros(Biblioteca biblioteca) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.biblioteca = biblioteca;
        this.bibliotecario = biblioteca.getBibliotecario();
        this.libros = biblioteca.getLibros();
        
        DefaultTableModel modeloTabla = (DefaultTableModel) tblListado.getModel();        
        bibliotecario.ordenarLibros(libros);        
        for (Libro libro : libros) {
            modeloTabla.addRow(new Object[] {
            libro.getCodigo(),
            libro.getAutor(),
            libro.getTitulo(),
            libro.getCantidad(),
            libro.getFechaPublicacion(),
            libro.getEditorial()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        lblListadoLibros = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        comboBoxFiltros = new javax.swing.JComboBox<>();
        fieldBusqueda = new javax.swing.JTextField();
        lblBusqueda = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnAplicarFiltro = new javax.swing.JButton();
        btnLimpiarFiltro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 153));
        pnlFrame.setLayout(null);

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Autor", "Titulo", "Copias", "Fecha Publicacion", "Editorial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListado);

        pnlFrame.add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 930, 402);

        lblListadoLibros.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblListadoLibros.setForeground(new java.awt.Color(0, 0, 0));
        lblListadoLibros.setText("Listado De Libros Existentes");
        pnlFrame.add(lblListadoLibros);
        lblListadoLibros.setBounds(360, 20, 270, 22);

        lblFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltrar.setText("Filtrar por:");
        pnlFrame.add(lblFiltrar);
        lblFiltrar.setBounds(40, 520, 80, 20);

        comboBoxFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Autor" }));
        comboBoxFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFiltrosActionPerformed(evt);
            }
        });
        pnlFrame.add(comboBoxFiltros);
        comboBoxFiltros.setBounds(140, 520, 140, 24);
        pnlFrame.add(fieldBusqueda);
        fieldBusqueda.setBounds(140, 560, 140, 24);

        lblBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lblBusqueda.setText("Item a buscar:");
        pnlFrame.add(lblBusqueda);
        lblBusqueda.setBounds(40, 560, 93, 20);

        btnCerrar.setText("Cerrar Listado");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCerrar);
        btnCerrar.setBounds(790, 590, 160, 40);

        btnAplicarFiltro.setText("Aplicar Filtro");
        btnAplicarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarFiltroActionPerformed(evt);
            }
        });
        pnlFrame.add(btnAplicarFiltro);
        btnAplicarFiltro.setBounds(140, 600, 140, 30);

        btnLimpiarFiltro.setText("Limpiar Filtro");
        btnLimpiarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltroActionPerformed(evt);
            }
        });
        pnlFrame.add(btnLimpiarFiltro);
        btnLimpiarFiltro.setBounds(330, 600, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFiltrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFiltrosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAplicarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarFiltroActionPerformed

    private void btnLimpiarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltroActionPerformed
        // TODO add your handling code here:
        fieldBusqueda.setText("");
    }//GEN-LAST:event_btnLimpiarFiltroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFiltro;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiarFiltro;
    private javax.swing.JComboBox<String> comboBoxFiltros;
    private javax.swing.JTextField fieldBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblListadoLibros;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JTable tblListado;
    // End of variables declaration//GEN-END:variables
}
