/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Estudiante;
import backend.Libro;
import backend.Prestamo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ronyrojas
 */
public class PrestamoLibro extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private Bibliotecario bibliotecario = new Bibliotecario();
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Libro> libros;
    private ArrayList<Prestamo> prestamos;
    private SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

    private ArrayList<Libro> librosTemp = new ArrayList();
    private Estudiante estudianteTemp = new Estudiante();
    private String fechaTemp;
    private boolean otroLibro = false;

    /**
     * Creates new form PrestamoLibro
     */
    public PrestamoLibro(Biblioteca biblioteca) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.biblioteca = biblioteca;
        this.estudiantes = biblioteca.getEstudiantes();
        this.libros = biblioteca.getLibros();
        this.prestamos = biblioteca.getPrestamos();
        btnVerificarDisponibilidad.setEnabled(false);
        btnRealizarPrestamo.setEnabled(false);
        calendario.setEnabled(false);
        btnListadoLibrosPrestar.setVisible(false);
        btnPrestarOtroLibro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblPrestamo = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        fieldCarnet = new javax.swing.JTextField();
        btnVerificarPrestamos = new javax.swing.JButton();
        lblLibro = new javax.swing.JLabel();
        fieldLibro = new javax.swing.JTextField();
        btnVerificarDisponibilidad = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRealizarPrestamo = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        btnPrestarOtroLibro = new javax.swing.JButton();
        btnListadoLibrosPrestar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(255, 102, 51));
        pnlFrame.setLayout(null);

        lblPrestamo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        lblPrestamo.setText("Prestamo Libro");
        pnlFrame.add(lblPrestamo);
        lblPrestamo.setBounds(210, 20, 150, 22);

        lblCarnet.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnet.setText("Carnet Estudiante: ");
        pnlFrame.add(lblCarnet);
        lblCarnet.setBounds(10, 60, 140, 22);

        fieldCarnet.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCarnet);
        fieldCarnet.setBounds(10, 80, 170, 30);

        btnVerificarPrestamos.setBackground(new java.awt.Color(0, 255, 255));
        btnVerificarPrestamos.setForeground(new java.awt.Color(0, 0, 255));
        btnVerificarPrestamos.setText("Verificar Prestamos");
        btnVerificarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPrestamosActionPerformed(evt);
            }
        });
        pnlFrame.add(btnVerificarPrestamos);
        btnVerificarPrestamos.setBounds(210, 80, 200, 30);

        lblLibro.setForeground(new java.awt.Color(0, 0, 255));
        lblLibro.setText("Codigo de Libro a Prestar: ");
        pnlFrame.add(lblLibro);
        lblLibro.setBounds(10, 140, 190, 22);

        fieldLibro.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldLibro);
        fieldLibro.setBounds(10, 160, 170, 30);

        btnVerificarDisponibilidad.setBackground(new java.awt.Color(0, 255, 255));
        btnVerificarDisponibilidad.setForeground(new java.awt.Color(0, 0, 255));
        btnVerificarDisponibilidad.setText("Verificar Disponibilidad");
        btnVerificarDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDisponibilidadActionPerformed(evt);
            }
        });
        pnlFrame.add(btnVerificarDisponibilidad);
        btnVerificarDisponibilidad.setBounds(210, 160, 200, 30);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCancelar);
        btnCancelar.setBounds(20, 390, 130, 30);

        btnRealizarPrestamo.setBackground(new java.awt.Color(0, 255, 255));
        btnRealizarPrestamo.setForeground(new java.awt.Color(0, 0, 255));
        btnRealizarPrestamo.setText("Realizar Prestamo");
        btnRealizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPrestamoActionPerformed(evt);
            }
        });
        pnlFrame.add(btnRealizarPrestamo);
        btnRealizarPrestamo.setBounds(210, 390, 170, 30);

        lblFecha.setForeground(new java.awt.Color(0, 0, 255));
        lblFecha.setText("Fecha de Prestamo:");
        pnlFrame.add(lblFecha);
        lblFecha.setBounds(10, 200, 150, 22);
        pnlFrame.add(calendario);
        calendario.setBounds(10, 220, 170, 30);

        btnPrestarOtroLibro.setText("Añadir libro a la lista");
        btnPrestarOtroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarOtroLibroActionPerformed(evt);
            }
        });
        pnlFrame.add(btnPrestarOtroLibro);
        btnPrestarOtroLibro.setBounds(20, 320, 200, 30);

        btnListadoLibrosPrestar.setText("Ver lista");
        btnListadoLibrosPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoLibrosPrestarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnListadoLibrosPrestar);
        btnListadoLibrosPrestar.setBounds(280, 320, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPrestamosActionPerformed
        // TODO add your handling code here:

        if (fieldCarnet.getText().isEmpty()) {
            String mensaje = "Complete los campos vacios";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (bibliotecario.isNumeric(fieldCarnet.getText())) {
                int carnet = Integer.parseInt(fieldCarnet.getText());
                int prestamosDisponibles = bibliotecario.verificarPrestamosEstudiante(estudiantes, carnet);
                if (prestamosDisponibles > 0) {

                    btnVerificarDisponibilidad.setEnabled(true);
                    btnVerificarPrestamos.setEnabled(false);
                    fieldCarnet.setEnabled(false);

                    String mensaje = "El estudiante tiene: " + prestamosDisponibles + " prestamos disponibles";
                    JOptionPane.showMessageDialog(null, mensaje, "Verificar Prestamos", JOptionPane.INFORMATION_MESSAGE);
                } else if (prestamosDisponibles == -1) {
                    String mensaje = "El estudiante con carnet: " + carnet + ", no existe";
                    JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    String mensaje = "El estudiante no tiene prestamos disponibles";
                    JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                String mensaje = "En el campo: Carnet,\nDebe ingresar un valor numerico entero positivo";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnVerificarPrestamosActionPerformed

    private void btnVerificarDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDisponibilidadActionPerformed
        // TODO add your handling code here:

        String codigoLibro = fieldLibro.getText();
        if (fieldLibro.getText().isEmpty()) {
            String mensaje = "Complete los campos vacios";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int copias = bibliotecario.verificarCopias(libros, codigoLibro);
            if (copias > 0) {

                boolean repetido = false;
                if (otroLibro) {
                    int indexLibroTemp = bibliotecario.buscarLibro(libros, fieldLibro.getText());
                    if (!libroRepetido(libros.get(indexLibroTemp).getCodigo())) {
                        btnPrestarOtroLibro.setEnabled(true);
                    } else {
                        repetido = true;
                        fieldLibro.setText("");
                        String mensaje = "El libro solicitado ya esta en la lista";
                        JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    btnRealizarPrestamo.setEnabled(true);
                    btnPrestarOtroLibro.setEnabled(true);
                    btnVerificarDisponibilidad.setEnabled(false);
                    fieldLibro.setEnabled(false);
                    calendario.setEnabled(true);
                }
                if (!repetido) {
                    String mensaje = "Hay: " + copias + " copias disponibles del libro";
                    JOptionPane.showMessageDialog(null, mensaje, "Verificar Copias", JOptionPane.INFORMATION_MESSAGE);
                }

            } else if (copias == -1) {
                String mensaje = "El libro con codigo: " + codigoLibro + ", no existe";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String mensaje = "No hay copias disponibles del libro solicitado";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVerificarDisponibilidadActionPerformed

    private void btnRealizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPrestamoActionPerformed
        // TODO add your handling code here:

        String fecha = "";
        try {
            fecha = formato.format(calendario.getDate());
        } catch (NullPointerException e) {
        }

        if (!otroLibro) {

            if (fecha == "") {
                String mensaje = "Ingrese la fecha del prestamo";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (bibliotecario.fechaValida(fecha)) {
                    bibliotecario.crearPrestamo(estudiantes, libros, prestamos, Integer.parseInt(fieldCarnet.getText()), fieldLibro.getText(), fecha);
                    String mensaje = "Prestamo creado correctamente";
                    JOptionPane.showMessageDialog(null, mensaje, "Crear prestamo", JOptionPane.INFORMATION_MESSAGE);
                    reiniciarValores();
                } else {
                    String mensaje = "Formato de fecha incorrecto (yyyy-mm-dd)";
                    JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else {
            if (!librosTemp.isEmpty()) {
                for (int i = 0; i < librosTemp.size(); i++) {
                    bibliotecario.crearPrestamo(estudiantes, libros, prestamos, Integer.parseInt(fieldCarnet.getText()), librosTemp.get(i).getCodigo(), fecha);
                }
                String mensaje = "Prestamos creados correctamente";
                JOptionPane.showMessageDialog(null, mensaje, "Crear prestamo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String mensaje = "No se ha realizado ningun prestamo porque la lista esta vacia";
                JOptionPane.showMessageDialog(null, mensaje, "Crear prestamo", JOptionPane.INFORMATION_MESSAGE);
            }

            librosTemp = new ArrayList();
            estudianteTemp = new Estudiante();
            fechaTemp = "";
            otroLibro = false;
            //contLibros = 0;

            reiniciarValores();
            btnListadoLibrosPrestar.setVisible(false);
        }

    }//GEN-LAST:event_btnRealizarPrestamoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPrestarOtroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarOtroLibroActionPerformed
        // TODO add your handling code here:
        fechaTemp = "";
        if (!otroLibro) {
            int indexEstudianteTemp = bibliotecario.buscarEstudiante(estudiantes, Integer.parseInt(fieldCarnet.getText()));
            estudianteTemp = estudiantes.get(indexEstudianteTemp);
            try {
                fechaTemp = formato.format(calendario.getDate());
            } catch (NullPointerException e) {
            }
        }

        if (estudianteTemp.getNumeroPrestamos() - librosTemp.size() > 0) {
            if (bibliotecario.fechaValida(fechaTemp) || otroLibro) {
                int indexLibroTemp = bibliotecario.buscarLibro(libros, fieldLibro.getText());
                librosTemp.add(libros.get(indexLibroTemp));

                btnListadoLibrosPrestar.setVisible(true);
                btnPrestarOtroLibro.setEnabled(false);

                fieldCarnet.setEnabled(false);
                fieldLibro.setEnabled(true);
                fieldLibro.setText("");
                btnVerificarDisponibilidad.setEnabled(true);
                calendario.setEnabled(false);
                otroLibro = true;

            } else {
                String mensaje = "Formato de fecha incorrecto (yyyy-mm-dd)";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            String mensaje = "Ya no se pueden añadir más libros a la lista porque el estudiante ya no tiene prestamos disponibles";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPrestarOtroLibroActionPerformed

    private void btnListadoLibrosPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoLibrosPrestarActionPerformed
        // TODO add your handling code here:
        ListadoLibrosPrestar llp = new ListadoLibrosPrestar(librosTemp);
        llp.setVisible(true);
    }//GEN-LAST:event_btnListadoLibrosPrestarActionPerformed

    private boolean libroRepetido(String codigoVerificar) {

        for (int i = 0; i < librosTemp.size(); i++) {
            if (librosTemp.get(i).getCodigo().equals(codigoVerificar)) {
                return true;
            }
        }
        return false;
    }

    private void reiniciarValores() {
        fieldCarnet.setText("");
        fieldLibro.setText("");
        calendario.setDate(null);
        btnVerificarPrestamos.setEnabled(true);
        fieldCarnet.setEnabled(true);
        fieldLibro.setEnabled(true);
        btnRealizarPrestamo.setEnabled(false);
        btnPrestarOtroLibro.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnListadoLibrosPrestar;
    private javax.swing.JButton btnPrestarOtroLibro;
    private javax.swing.JButton btnRealizarPrestamo;
    private javax.swing.JButton btnVerificarDisponibilidad;
    private javax.swing.JButton btnVerificarPrestamos;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JTextField fieldCarnet;
    private javax.swing.JTextField fieldLibro;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
