/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Estudiante;
import backend.Libro;
import backend.Prestamo;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ronyrojas
 */
public class PrestamoLibro extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private Bibliotecario bibliotecario = new Bibliotecario();
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Libro> libros;
    private ArrayList<Prestamo> prestamos;

    /**
     * Creates new form PrestamoLibro
     */
    public PrestamoLibro(Biblioteca biblioteca) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.biblioteca = biblioteca;
        this.estudiantes = biblioteca.getEstudiantes();
        this.libros = biblioteca.getLibros();
        this.prestamos = biblioteca.getPrestamos();
        btnVerificarDisponibilidad.setEnabled(false);
        btnRealizarPrestamo.setEnabled(false);
        fieldFecha.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblPrestamo = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        fieldCarnet = new javax.swing.JTextField();
        btnVerificarPrestamos = new javax.swing.JButton();
        lblLibro = new javax.swing.JLabel();
        fieldLibro = new javax.swing.JTextField();
        btnVerificarDisponibilidad = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRealizarPrestamo = new javax.swing.JButton();
        fieldFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(255, 102, 51));
        pnlFrame.setLayout(null);

        lblPrestamo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        lblPrestamo.setText("Prestamo Libro");
        pnlFrame.add(lblPrestamo);
        lblPrestamo.setBounds(210, 20, 150, 22);

        lblCarnet.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnet.setText("Carnet Estudiante: ");
        pnlFrame.add(lblCarnet);
        lblCarnet.setBounds(10, 60, 140, 18);

        fieldCarnet.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCarnet);
        fieldCarnet.setBounds(10, 80, 170, 24);

        btnVerificarPrestamos.setBackground(new java.awt.Color(0, 255, 255));
        btnVerificarPrestamos.setForeground(new java.awt.Color(0, 0, 255));
        btnVerificarPrestamos.setText("Verificar Prestamos");
        btnVerificarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPrestamosActionPerformed(evt);
            }
        });
        pnlFrame.add(btnVerificarPrestamos);
        btnVerificarPrestamos.setBounds(210, 80, 200, 24);

        lblLibro.setForeground(new java.awt.Color(0, 0, 255));
        lblLibro.setText("Codigo de Libro a Prestar: ");
        pnlFrame.add(lblLibro);
        lblLibro.setBounds(10, 140, 190, 18);

        fieldLibro.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldLibro);
        fieldLibro.setBounds(10, 160, 170, 24);

        btnVerificarDisponibilidad.setBackground(new java.awt.Color(0, 255, 255));
        btnVerificarDisponibilidad.setForeground(new java.awt.Color(0, 0, 255));
        btnVerificarDisponibilidad.setText("Verificar Disponibilidad");
        btnVerificarDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDisponibilidadActionPerformed(evt);
            }
        });
        pnlFrame.add(btnVerificarDisponibilidad);
        btnVerificarDisponibilidad.setBounds(210, 160, 200, 24);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnCancelar);
        btnCancelar.setBounds(20, 390, 130, 24);

        btnRealizarPrestamo.setBackground(new java.awt.Color(0, 255, 255));
        btnRealizarPrestamo.setForeground(new java.awt.Color(0, 0, 255));
        btnRealizarPrestamo.setText("Realizar Prestamo");
        btnRealizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPrestamoActionPerformed(evt);
            }
        });
        pnlFrame.add(btnRealizarPrestamo);
        btnRealizarPrestamo.setBounds(210, 390, 170, 24);

        fieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldFecha);
        fieldFecha.setBounds(10, 220, 170, 24);

        lblFecha.setForeground(new java.awt.Color(0, 0, 255));
        lblFecha.setText("Fecha de Prestamo:");
        pnlFrame.add(lblFecha);
        lblFecha.setBounds(10, 200, 150, 18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPrestamosActionPerformed
        // TODO add your handling code here:

        if (fieldCarnet.getText().isEmpty()) {
            String mensaje = "Complete los campos vacios";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (bibliotecario.isNumeric(fieldCarnet.getText())) {
                int carnet = Integer.parseInt(fieldCarnet.getText());
                int prestamosDisponibles = bibliotecario.verificarPrestamosEstudiante(estudiantes, carnet);
                if (prestamosDisponibles > 0) {

                    btnVerificarDisponibilidad.setEnabled(true);
                    btnVerificarPrestamos.setEnabled(false);
                    fieldCarnet.setEnabled(false);

                    String mensaje = "El estudiante tiene: " + prestamosDisponibles + " prestamos disponibles";
                    JOptionPane.showMessageDialog(null, mensaje, "Verificar Prestamos", JOptionPane.INFORMATION_MESSAGE);
                } else if (prestamosDisponibles == -1) {
                    String mensaje = "El estudiante con carnet: " + carnet + ", no existe";
                    JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    String mensaje = "El estudiante no tiene prestamos disponibles";
                    JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                String mensaje = "En el campo: Carnet,\nDebe ingresar un valor numerico entero positivo";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnVerificarPrestamosActionPerformed

    private void btnVerificarDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDisponibilidadActionPerformed
        // TODO add your handling code here:

        String codigoLibro = fieldLibro.getText();
        if (fieldLibro.getText().isEmpty()) {
            String mensaje = "Complete los campos vacios";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int copias = bibliotecario.verificarCopias(libros, codigoLibro);
            if (copias > 0) {
                btnRealizarPrestamo.setEnabled(true);
                btnVerificarDisponibilidad.setEnabled(false);
                fieldLibro.setEnabled(false);
                fieldFecha.setEnabled(true);

                String mensaje = "Hay: " + copias + " copias disponibles del libro";
                JOptionPane.showMessageDialog(null, mensaje, "Verificar Copias", JOptionPane.INFORMATION_MESSAGE);
            } else if (copias == -1) {
                String mensaje = "El libro con codigo: " + codigoLibro + ", no existe";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String mensaje = "No hay copias disponibles del libro solicitado";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVerificarDisponibilidadActionPerformed

    private void btnRealizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPrestamoActionPerformed
        // TODO add your handling code here:
        String fecha = fieldFecha.getText();

        if (fecha.isEmpty()) {
            String mensaje = "Ingrese la fecha del prestamo";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (bibliotecario.fechaValida(fecha)) {
                bibliotecario.crearPrestamo(estudiantes, libros, prestamos, Integer.parseInt(fieldCarnet.getText()), fieldLibro.getText(), fecha);
                String mensaje = "Prestamo creado correctamente";
                JOptionPane.showMessageDialog(null, mensaje, "Crear prestamo", JOptionPane.INFORMATION_MESSAGE);

                fieldCarnet.setText("");
                fieldLibro.setText("");
                fieldFecha.setText("");
                btnVerificarPrestamos.setEnabled(true);
                fieldCarnet.setEnabled(true);
                fieldLibro.setEnabled(true);
                btnRealizarPrestamo.setEnabled(false);
            } else {
                String mensaje = "Formato de fecha incorrecto (yyyy-mm-dd)";
                JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnRealizarPrestamoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRealizarPrestamo;
    private javax.swing.JButton btnVerificarDisponibilidad;
    private javax.swing.JButton btnVerificarPrestamos;
    private javax.swing.JTextField fieldCarnet;
    private javax.swing.JTextField fieldFecha;
    private javax.swing.JTextField fieldLibro;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
