/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Estudiante;
import java.util.ArrayList;

/**
 *
 * @author ronyrojas
 */
public class RegistroEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEstudiante
     */
    
    private Biblioteca biblioteca;
    private ArrayList<Estudiante> estudiantes;
    
    public RegistroEstudiante(Biblioteca biblioteca) {
        initComponents();
        
        this.biblioteca = biblioteca;
        estudiantes = biblioteca.getEstudiantes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblRegistarEstudiante = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        fieldCarnet = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        fieldCodigoCarrera = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        fieldFecha = new javax.swing.JTextField();
        btnListadoEstudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 153, 0));
        pnlFrame.setLayout(null);

        lblRegistarEstudiante.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblRegistarEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistarEstudiante.setText("Registrar Nuevo Estudiante");
        pnlFrame.add(lblRegistarEstudiante);
        lblRegistarEstudiante.setBounds(140, 20, 260, 40);

        lblCarnet.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnet.setText("Carnet:");
        pnlFrame.add(lblCarnet);
        lblCarnet.setBounds(50, 90, 60, 18);

        lblNombre.setForeground(new java.awt.Color(0, 0, 255));
        lblNombre.setText("Nombre:");
        pnlFrame.add(lblNombre);
        lblNombre.setBounds(50, 150, 60, 18);

        lblCarrera.setForeground(new java.awt.Color(0, 0, 255));
        lblCarrera.setText("Codigo de Carrera:");
        pnlFrame.add(lblCarrera);
        lblCarrera.setBounds(50, 210, 130, 18);

        lblFecha.setForeground(new java.awt.Color(0, 0, 255));
        lblFecha.setText("Fecha de Nacimiento:");
        pnlFrame.add(lblFecha);
        lblFecha.setBounds(50, 270, 150, 18);

        fieldCarnet.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCarnet);
        fieldCarnet.setBounds(50, 110, 150, 24);

        fieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldNombre);
        fieldNombre.setBounds(50, 170, 150, 24);

        fieldCodigoCarrera.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldCodigoCarrera);
        fieldCodigoCarrera.setBounds(50, 230, 150, 24);

        btnRegistrar.setBackground(new java.awt.Color(0, 204, 204));
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnRegistrar);
        btnRegistrar.setBounds(50, 350, 150, 30);

        fieldFecha.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrame.add(fieldFecha);
        fieldFecha.setBounds(50, 300, 150, 24);

        btnListadoEstudiantes.setBackground(new java.awt.Color(0, 204, 204));
        btnListadoEstudiantes.setForeground(new java.awt.Color(0, 0, 255));
        btnListadoEstudiantes.setText("Ver Listado Estudiantes");
        btnListadoEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoEstudiantesActionPerformed(evt);
            }
        });
        pnlFrame.add(btnListadoEstudiantes);
        btnListadoEstudiantes.setBounds(290, 350, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int carnet = Integer.parseInt(fieldCarnet.getText());
        String nombre = fieldNombre.getText();
        int codigoCarrera = Integer.parseInt(fieldCodigoCarrera.getText());
        String fechaNacimiento = fieldFecha.getText();
        
        estudiantes.add(new Estudiante(carnet, nombre, codigoCarrera, fechaNacimiento));
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnListadoEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoEstudiantesActionPerformed
        // TODO add your handling code here:
        System.out.println("boton registrar");
        ListadoEstudiantes listadoEstudiantes = new ListadoEstudiantes();
        listadoEstudiantes.setVisible(true);
    }//GEN-LAST:event_btnListadoEstudiantesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListadoEstudiantes;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField fieldCarnet;
    private javax.swing.JTextField fieldCodigoCarrera;
    private javax.swing.JTextField fieldFecha;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistarEstudiante;
    private javax.swing.JPanel pnlFrame;
    // End of variables declaration//GEN-END:variables
}
