/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Biblioteca;
import backend.Bibliotecario;
import backend.Estudiante;
import backend.Filtro;
import backend.Libro;
import backend.Prestamo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herberthreyes
 */
public class Reporte5 extends javax.swing.JFrame {

    private Biblioteca biblioteca;
    private Bibliotecario bibliotecario = new Bibliotecario();
    private ArrayList<Prestamo> prestamos;
    private ArrayList<Estudiante> estudiantes;
    private ArrayList<Libro> libros;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form Reporte5
     */
    public Reporte5(Biblioteca biblioteca) {
        initComponents();
        this.biblioteca = biblioteca;
        this.prestamos = biblioteca.getPrestamos();
        this.estudiantes = biblioteca.getEstudiantes();
        this.libros = biblioteca.getLibros();

        this.modeloTabla = (DefaultTableModel) tblPrestamos.getModel();
        filtro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrame = new javax.swing.JPanel();
        lblPretamos = new javax.swing.JLabel();
        lblCarnetEstudiante = new javax.swing.JLabel();
        fieldCarnetEstudiante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFrame.setBackground(new java.awt.Color(0, 204, 102));
        pnlFrame.setLayout(null);

        lblPretamos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblPretamos.setForeground(new java.awt.Color(0, 0, 0));
        lblPretamos.setText("Libros prestados actualmente a un estudiante");
        pnlFrame.add(lblPretamos);
        lblPretamos.setBounds(260, 30, 399, 30);

        lblCarnetEstudiante.setForeground(new java.awt.Color(0, 0, 255));
        lblCarnetEstudiante.setText("Carnet del estudiante: ");
        pnlFrame.add(lblCarnetEstudiante);
        lblCarnetEstudiante.setBounds(20, 80, 150, 30);

        fieldCarnetEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldCarnetEstudianteKeyReleased(evt);
            }
        });
        pnlFrame.add(fieldCarnetEstudiante);
        fieldCarnetEstudiante.setBounds(200, 80, 120, 30);

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet Estudiante", "Nombre", "Codigo Libro", "Titulo", "Autor", "Cantidad Copias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrestamos);

        pnlFrame.add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 800, 402);

        btnRegresar.setBackground(new java.awt.Color(255, 0, 51));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlFrame.add(btnRegresar);
        btnRegresar.setBounds(300, 550, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void fieldCarnetEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCarnetEstudianteKeyReleased
        // TODO add your handling code here:
        filtro();
    }//GEN-LAST:event_fieldCarnetEstudianteKeyReleased

    private void filtro(){
        Filtro filtro = new Filtro();
        int carnetFiltro = -1;
        if (bibliotecario.isNumeric(fieldCarnetEstudiante.getText())) {
            carnetFiltro = Integer.parseInt(fieldCarnetEstudiante.getText());
        }
        filtro.filtroPrestamoLibro(tblPrestamos.getRowCount(), carnetFiltro, modeloTabla, prestamos, libros, estudiantes);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField fieldCarnetEstudiante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarnetEstudiante;
    private javax.swing.JLabel lblPretamos;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JTable tblPrestamos;
    // End of variables declaration//GEN-END:variables
}
